### ISSUE TITLE
EntityUtils.toString(entity) throwing OutOfMemory errors

### ISSUE THREAD

**Issue by ishratkhan** [liveservices/LiveSDK-for-Android#46]
I am facing OufOfMemory errors inside LiveSDK, Please help.

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.OutOfMemoryError
at org.apache.http.util.CharArrayBuffer.<init>(CharArrayBuffer.java:55)
at org.apache.http.util.EntityUtils.toString(EntityUtils.java:131)
at org.apache.http.util.EntityUtils.toString(EntityUtils.java:146)
at com.microsoft.live.JsonResponseHandler.handleResponse(JsonResponseHandler.java:50)
at com.microsoft.live.JsonResponseHandler.handleResponse(JsonResponseHandler.java:41)
at com.microsoft.live.ApiRequest.execute(ApiRequest.java:243)
at com.microsoft.live.ApiRequestAsync.doInBackground(ApiRequestAsync.java:171)
at com.microsoft.live.ApiRequestAsync.doInBackground(ApiRequestAsync.java:36)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 4 more

**Comment by peternied** [comment]
When encountering out of memory errors a callstack isn't going to tell you much.  I'd recommend using the tooling from Android to look into the state of the application and its usage of memory https://developer.android.com/tools/debugging/debugging-memory.html 

If you can get traces that point to a memory leak within the LiveSDK code specificly along with those artifacts I'd be happy to investigate.

**Comment by Sarasranglt** [comment]
did you find out why did it happen. The same stack trace happened to me ..
