### ISSUE TITLE
Crash when attempting connection with no internet connection

### ISSUE THREAD

**Issue by bright-tools** [liveservices/LiveSDK-for-Android#52]
When invoking LiveAuthClient.login() with all network access disabled (Android 4.4.4), the app crashes with the following stacktrace:

    05-29 15:51:58.343    W/System.err﹕ java.lang.NullPointerException
    05-29 15:51:58.343    W/System.err﹕ at com.microsoft.live.AuthorizationRequest$OAuthDialog$AuthorizationWebViewClient.onPageFinished(AuthorizationRequest.java:103)
    05-29 15:51:58.347    W/System.err﹕ at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:455)
    05-29 15:51:58.347    W/System.err﹕ at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver.didFinishLoad(AwContentsClient.java:62)

**Comment by bright-tools** [comment]
Dupe of #50, sorry.
